### ISSUE TITLE
Allow me to set the color of snowflakes

### ISSUE THREAD

**Issue by Bojhan** [ramuuns/snowflakes#1]
Hi,

Just wondering if this can be set somehow? My site has a white background - where ideally I can offset the white by a little bit to still make it shine!

Thanks for this awesome project :+1:

**Comment by ramuuns** [comment]
Hi,

I've added a color option to the constructor - so now when you initialize the snowflakes you can do something like this `window.snowflakes({color:"{yourcolor}"})` (where {yourcolor} is any canvas/css supported color.

**Comment by Bojhan** [comment]
Awesome!

**Comment by mrserge** [comment]
Jesus, it's true!

**Comment by Bojhan** [comment]
Hmm, this doesnt seem to work propperly or I am missing something (probally the latter).

window.snowflakes({amount: 700, nuclearMode: false, color:"{#FFFFFF}"});

Still gives me kind of gray/black looking snowflakes.

**Comment by ramuuns** [comment]
try
`window.snowflakes({amount: 700, nuclearMode: false, color:"#FFFFFF"});`
